### ISSUE TITLE
catch completion events and execute the action

### ISSUE THREAD

**Issue by pcause** [therden/packrat#10]
Does obsidian have an API (or does tasks) that allows you to catch a completion event?  If so, it would be great to have packrat catch the event and perform the action on the just completed task.  And support tasks without recurrence in this case as well.

**Comment by therden** [comment]
Hello @pcause.  

I believe that the Obsidian API _does_ expose a 'completion' event -- however, native Obsidian's action is limited to updating the markdown checklist item prefix string, changing `- [ ]` to `- [x]`.  

The Tasks plugin [optionally] overrides this native/default behavior, such that an item marked as Complete has a "Done" emoji ✅ and the date appended as a suffix to the Todo item.  It also auto-generates the next instance of the item contains a Recurrent rule.

So far as I'm aware, Tasks does _not_ presently provide a way to hook into its completion event.  (But here I'll mention Tasks' current Maintainer, @claremacrae, by way of checking that belief.) That's why I designed the [Packrat plugin](https://github.com/therden/packrat) to act _after the fact_ on the completed recurring items within a given note based on the trigger values they contain.

I agree 100% with you (and @kmaustral, @imeed166, @blackpeasy) that making Packrat-style trigger value-based actions occur _at the time an items is completed_ would be superior to my plugin's current approach.  If Tasks does ever support it and my Typescript skills prove to be up to the challenge, I'll try to make it so.

**Comment by profucius** [comment]
I too would like to see this feature implemented, whether in Obsidian, Tasks, or Packrat.

In the meantime, @therden what do you think about adding a command to your plugin which scans the vault and performs the action in every file? This would technically be a workaround to it being handled automatically instantly, at least I would be able to schedule a job that performs this batch command perhaps daily. Thoughts?

**Comment by therden** [comment]
Hello @profucius.

If my renewed efforts to get equivalent _real-time_ processing of completed items added to **Tasks** itself are unsuccessful, then I intend to add a second **Packrat** command for "whole vault" scanning that will rely on a note Property (formerly YAML front-matter key:value) to identify each note on which **Packrat** should operate.

For now, however, I am Closing this issue.

**Comment by pcause** [comment]
I like to put tags on items in various pages and I don't think about or want to have to go back and add properties.  I know this makes it easier but i think is isn't particularly user friendly.
