### ISSUE TITLE
Error: File Already Exists

### ISSUE THREAD

**Issue by Carriolan** [therden/packrat#12]
Hi I am running v1.3.5 Obsidian on a Mac with Tasks 3.10.0 and Packrat v0.4.1. I have put all my recurring tasks into a single note and have inserted either %%done_log%% or %%done_end%% immediately after the task description of each task. I have setup a blank Archive.md file in the 400 Project folder and entered the path and file name in the Packrat Options.

With the recurring task note active, the first time I run Packrat the completed tasks are moved to the Archive.md file without issue. However the second and subsequent times, I get the error message: "Error: File Already Exists"

I assume that the file that the Packrat error message is referring to, is Archive.md. Any suggestions please?

**Comment by therden** [comment]
Hello @Carriolan.  I apologize for this extremely delayed reply.  

If you were unable to resolve the problem you described but are still interested in trying, please let me know at your earliest convenience.  Otherwise, if I haven't heard back from you within a couple of weeks, I'll close this Issue .

(I don't have access to a Mac myself, and I haven't heard from other Mac users about the issue you've reported.  The plugin works on both Windows and Linux systems.)
